//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVerse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Customer_id { get; set; }
        public Nullable<long> HomePhone { get; set; }
        public Nullable<long> WorkPhone { get; set; }
        public Nullable<long> CellPhone { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
